name: Documentation
on:
  push:
    branches:
      - main
      - initial-release
permissions:
  contents: write
  id-token: write
  pull-requests: write
concurrency:
  # canceling actions from older commits:
  # https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pinder & docs dependencies
        shell: bash
        run: |
          python -m pip install .[data,docs]
          python -m pip install 'torch<2.2'
          python -m pip install torch-cluster -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
          python -m pip uninstall scikit-learn -y
          python -m pip install "scikit-learn<=1.2.2"
      - name: Sphinx build
        shell: bash
        run: |
          cd docs
          ./build.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          force_orphan: true
